AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 12
