version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: Build docker image
          command: docker-compose build

      - run:
          name: Test in Docker
          command: docker-compose up

      - run:
          name: Down docker containers
          command: docker-compose down
